### ISSUE TITLE
Adding additional packages to flake dev env

### ISSUE THREAD

**Issue by ruler501** [on-nix/python#20]
For tensorflow specifically I need to include Cuda and a few other dependencies as well as add them to LD_LIBRARY_PATH. It's not clear how to modify the `.env` output to allow this customization.

**Comment by OmnipotentEntity** [comment]
I have also been banging my head against this problem for a few hours now.  There doesn't seem to be an easy way to hook into the environment building process, nor is there a way to inject the dependencies into the environment after the fact.

**Comment by kamadorueda** [comment]
@OmnipotentEntity @ruler501 you may want to have a look at: https://github.com/on-nix/python/issues/28#issuecomment-1029507435
