### ISSUE TITLE
[package request] - PySide6

### ISSUE THREAD

**Issue by uralbash** [on-nix/python#24]
# Package Request

**Comment by milahu** [comment]
pyside6 is part of https://github.com/NixOS/nixpkgs/pull/141883
build is passing
blocked by my laziness : P
pyside6 takes surprisingly long to build ... makes sense to cache

**Comment by kamadorueda** [comment]
pyside6 was quite fast to build here, added in: https://github.com/on-nix/python/commit/387a74b8a2f65ec76a8780b193d84fb98d2c2c39
