### ISSUE TITLE
[package request] - python-lsp-server

### ISSUE THREAD

**Issue by fleimgruber** [on-nix/python#26]
# Package Request

When trying to install `python-lsp-server` I get

```
Ups! Project "python-lsp-server" is not On Nix already.
```

I found it in https://github.com/on-nix/python/blob/main/makes/crawl/projects.lst, but not on https://python.on-nix.com/. Are there plans to support it?

**Comment by kamadorueda** [comment]
Just added it: https://python.on-nix.com/projects/python-lsp-server-1.3.3-python39/

Please let me know if it works appropriately

**Comment by fleimgruber** [comment]
Works perfectly, thanks for the prompt fix as always!
