### ISSUE TITLE
[package request] - jsons

### ISSUE THREAD

**Issue by ShowierData9978-Alt** [on-nix/python#32]
# Package Request

https://github.com/ramonhagenaars/jsons
https://libraries.io/pypi/jsons

**Comment by ShowierData9978-Alt** [comment]
hi?

**Comment by kamadorueda** [comment]
hi

**Comment by kamadorueda** [comment]
Added in: https://github.com/on-nix/python/commit/f8b6a246ee38721482912e9ce646078e108fb69c
