### ISSUE TITLE
[package request] - music21

### ISSUE THREAD

**Issue by fleimgruber** [on-nix/python#41]
# Package Request

This library is a music theory heavyweight and I think a good addition to Python on-nix.

https://web.mit.edu/music21/
https://pypi.org/project/music21/
https://github.com/cuthbertLab/music21

**Comment by fleimgruber** [comment]
I also found the package in https://github.com/on-nix/python/blob/main/makes/crawl/projects.lst - by the way, what is its purpose? I guess on-nix is used in makes?

**Comment by kamadorueda** [comment]
@fleimgruber that projects.lst is just a priority queue for the most used python projects, it was used at the beginning of the project to prioritize packaging the most popular ones

I just added music21, let me know if it works correctly :)

**Comment by fleimgruber** [comment]
Thanks for clarification and adding the package so quickly! Works for me!
